let g:airline_theme="solarized"
let g:airline_powerline_fonts = 1
let g:airline_section_y="" "Dont show file encoding/format
let g:airline_section_x="" "Dont show file encoding/format
let g:airline_section_z="%l/%L %c" "line/totallines column
let g:airline_skip_empty_sections=1
let g:airline#parts#ffenc#skip_expected_string='utf-8[unix]'
let g:airline_solarized_bg="dark"
let g:airline#extensions#tabline#enabled = 1
